---
title: "disgenet curated enrichment"
author: "Kayla Johnson"
date: '2022-06-14'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(knitr)
library(kableExtra)
library(UpSetR)
library(tidyverse)
library(RColorBrewer)
library(pheatmap)
library(colorspace)
```

```{r include=FALSE}
# read enrichment results
ndisc <- read_tsv("../../results/naive_sex_prediction_ranks/disgenetC_enrichment.tsv") %>% 
  rename(zscore = combined_zscore) %>% 
  rename(term_id = term)

# line to make palette with colorspace gui
# choose_palette(pal = diverging_hcl, n = 7L, parent = NULL, gui = "tcltk")

# blue/orange palette
light_bo_div <- diverge_hcl(11, c = 100, h = c(260, 35), l = c(50, 90), rev = T)
#blue half of palette
orange_palette <- sequential_hcl(7, c = 100, h = 35, l = c(50, 90))
blue_palette <- sequential_hcl(7, c = 100, h = 260, l = c(50, 90), rev = T)

# dark colors hex codes blue "#1c4587ff"/ orange "#783f04ff"
#blue/orange using on slides for M/F
fm_palette <- c("#6fa8dcff", "#e69138ff")

# order of age groups
fine_ag_order <- c("fetus", "infant", "young_child", "child", 
                                   "adolescent", "young_adult", "adult", 
                                   "middle_adult", "older_adult", "old_adult", "elderly")

age_ranges <- c("< 0", "[0-2]", "(2-8]", "(8-12]", "(12-20]", 
                "(20-35]", "(35-45]", "(45-60]", "(60-70]", "(70-80]", "> 80")

ar_tibble <- tibble(age_group = fine_ag_order, age_range = age_ranges, ag_number = c(1:11))

# add age range col to ndisc
ndisc <- left_join(ndisc, ar_tibble, by = "age_group")

ndisc <- ndisc %>% filter(abs(zscore) > 3) %>% 
  mutate(zscore = ifelse(zscore > 5, 5, zscore)) %>% 
  mutate(zscore = ifelse(zscore < -5, -5, zscore))
```

```{r make_zscore_heatmap, include=FALSE}
make_fbias_zscore_heatmap <- function(df){
  
  # set up matrix for heatmap
  row_names <- age_ranges
  col_names <- df %>% pull(term_id) %>% unique()
  
  mat <- matrix(rep(0, length(row_names) * length(col_names)), nrow = length(row_names))
  rownames(mat) <- row_names
  colnames(mat) <- col_names
  
  for (ar in row_names){
    for (t in col_names){
      zs <- df %>% 
        filter(age_range == !!ar) %>% 
        filter(term_id == !!t) %>% 
        pull(zscore)
      if (length(zs) == 0){
        zs <- 0
      }
      mat[ar, t] <- zs
    }
  }
  
  heatmap <- pheatmap(mat, color = blue_palette, 
                      cluster_rows = F, cluster_cols = T)
  return(heatmap)
}
```

```{r make_zscore_heatmap, include=FALSE}
make_mbias_zscore_heatmap <- function(df){
  
  # set up matrix for heatmap
  row_names <- age_ranges
  col_names <- df %>% pull(term_id) %>% unique()
  
  mat <- matrix(rep(0, length(row_names) * length(col_names)), nrow = length(row_names))
  rownames(mat) <- row_names
  colnames(mat) <- col_names
  
  for (ar in row_names){
    for (t in col_names){
      zs <- df %>% 
        filter(age_range == !!ar) %>% 
        filter(term_id == !!t) %>% 
        pull(zscore)
      if (length(zs) == 0){
        zs <- 0
      }
      mat[ar, t] <- zs
    }
  }
  
  heatmap <- pheatmap(mat, color = orange_palette, 
                      cluster_rows = F, cluster_cols = T)
  return(heatmap)
}
```

```{r make_zscore_heatmap, include=FALSE}
make_zscore_heatmap <- function(df){
  
  # set up matrix for heatmap
  row_names <- age_ranges
  col_names <- df %>% pull(term_id) %>% unique()
  
  mat <- matrix(rep(0, length(row_names) * length(col_names)), nrow = length(row_names))
  rownames(mat) <- row_names
  colnames(mat) <- col_names
  
  for (ar in row_names){
    for (t in col_names){
      zs <- df %>% 
        filter(age_range == !!ar) %>% 
        filter(term_id == !!t) %>% 
        pull(zscore)
      if (length(zs) == 0){
        zs <- 0
      }
      mat[ar, t] <- zs
    }
  }
  
  heatmap <- pheatmap(mat, color = light_bo_div, 
                      cluster_rows = F, cluster_cols = T)
  return(heatmap)
}
```

```{r}
female_bias_terms <- ndisc %>% filter(zscore > 0) %>% pull(term_id) %>% unique()
male_bias_terms <- ndisc %>% filter(zscore < 0) %>% pull(term_id) %>% unique()
both_bias_terms <- ndisc %>% 
  filter(term_id %in% female_bias_terms & term_id %in% male_bias_terms) %>% 
  pull(term_id)
female_bias_only_terms <- female_bias_terms[!female_bias_terms %in% both_bias_terms]
male_bias_only_terms <- male_bias_terms[!male_bias_terms %in% both_bias_terms]
```

```{r}
female_bias_only_ndisc <- ndisc %>% filter(term_id %in% female_bias_only_terms)
male_bias_only_ndisc <- ndisc %>% filter(term_id %in% male_bias_only_terms)
both_bias_ndisc <- ndisc %>% filter(term_id %in% both_bias_terms)
```

```{r}
female_bias_only_ndisc_heatmap <- make_fbias_zscore_heatmap(female_bias_only_ndisc)
```
```{r}
male_bias_only_ndisc_heatmap <- make_mbias_zscore_heatmap(male_bias_only_ndisc)
```

```{r}
both_bias_ndisc_heatmap <- make_zscore_heatmap(both_bias_ndisc)
```

```{r}
ggsave("~/Desktop/female_bias_only_ndisc_heatmap.pdf", width = 14, height = 8, 
       plot = female_bias_only_ndisc_heatmap)
ggsave("~/Desktop/male_bias_only_ndisc_heatmap.pdf", width = 14, height = 8, 
       plot = male_bias_only_ndisc_heatmap)
ggsave("~/Desktop/both_bias_ndisc_heatmap.pdf", width = 14, height = 8, 
       plot = both_bias_ndisc_heatmap)
```

