---
title: "gene_set_numbers"
author: "Kayla Johnson"
date: '2022-06-15'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(knitr)
library(tidyverse)
library(RColorBrewer)
library(pheatmap)
library(colorspace)
library(Matrix)
```

```{r data_read, include=FALSE}
# read enrichment results
mwgobp <- read_tsv("../../results/elasticnet_LR_model_weights/gobp_enrichment.tsv") %>% 
  rename(zscore = combined_zscore) %>% 
  rename(term_id = term)

mwsagd <- read_tsv("../../results/elasticnet_LR_model_weights/sagd_enrichment.tsv") %>% 
  rename(zscore = combined_zscore) %>% 
  rename(term_id = term)

mwdisc <- read_tsv("../../results/elasticnet_LR_model_weights/disgenetC_enrichment.tsv") %>% 
  rename(zscore = combined_zscore) %>% 
  rename(term_id = term)

mwmp <- read_tsv("../../results/elasticnet_LR_model_weights/mp_enrichment.tsv") %>% 
  rename(zscore = combined_zscore) %>% 
  rename(term_id = term)

mwgtex <- read_tsv("../../results/elasticnet_LR_model_weights/gtex_enrichment.tsv") %>% 
  rename(zscore = combined_zscore) %>% 
  rename(term_id = term)

mwguo <- read_tsv("../../results/elasticnet_LR_model_weights/guo_enrichment.tsv") %>% 
  rename(zscore = combined_zscore) %>% 
  rename(term_id = term)

mwgwas <- read_tsv("../../results/elasticnet_LR_model_weights/gwas_enrichment.tsv") %>% 
  rename(zscore = combined_zscore) %>% 
  rename(term_id = term)

# number of genes in all genesets
ngenes <- read_tsv("~/projects/age-sex-prediction/final_list-rank-zscore_gene_enrichment_analyses/data/gene_sets/number_genes_in_RNAseq-Mircroarray_commonset.tsv")

# line to make palette with colorspace gui
# choose_palette(pal = diverging_hcl, n = 7L, parent = NULL, gui = "tcltk")


brbg <- brewer.pal(11, "BrBG")
brbg_palette <- c(colorRampPalette(c(brbg[1], brbg[6]))(21),
    colorRampPalette(c(brbg[6], brbg[11]))(21)[-1])
#blue/orange using on slides for M/F
fm_palette <- c("#6fa8dcff", "#e69138ff")
```

```{r add_age_range, include=FALSE}
# order of age groups
fine_ag_order <- c("fetus", "infant", "young_child", "child", 
                                   "adolescent", "young_adult", "adult", 
                                   "middle_adult", "older_adult", "old_adult", "elderly")

age_ranges <- c("< 0", "[0-2]", "(2-8]", "(8-12]", "(12-20]", 
                "(20-35]", "(35-45]", "(45-60]", "(60-70]", "(70-80]", "> 80")

ar_tibble <- tibble(age_group = fine_ag_order, age_range = age_ranges, ag_number = c(1:11))

# add age range col to dfs
mwgobp <- left_join(mwgobp, ar_tibble, by = "age_group")
mwsagd <- left_join(mwsagd, ar_tibble, by = "age_group")
mwdisc <- left_join(mwdisc, ar_tibble, by = "age_group")
mwmp <- left_join(mwmp, ar_tibble, by = "age_group")
mwgtex <- left_join(mwgtex, ar_tibble, by = "age_group")
mwguo <- left_join(mwguo, ar_tibble, by = "age_group")
mwgwas <- left_join(mwgwas, ar_tibble, by = "age_group")
```

```{r}
make_heatmap <- function(df, s){
  
  keep_terms <- df %>% 
    filter(sex == s) %>% 
    filter(abs(zscore) > 2) %>% 
    group_by(term_id) %>% 
    tally() %>% 
    filter(n >3) %>% 
    pull(term_id)
    
    
  cut_df <- df %>% 
    filter(sex == s) %>% 
    mutate(zscore = ifelse(zscore > 5, 5, zscore)) %>% 
    mutate(zscore = ifelse(zscore < -5, -5, zscore)) %>% 
    filter(term_id %in% keep_terms)
  
  df_terms <- tibble(term_id = unique(cut_df$term_id), term_num = c(1:length(unique(cut_df$term_id))))
  cut_df <- left_join(cut_df, df_terms, by = "term_id")
  
  cut_mat <- as.matrix(with(cut_df, sparseMatrix(ag_number, term_num, x=zscore)))

  plot <- pheatmap(cut_mat, display_numbers = F, color = brbg_palette)
  
  return(plot)
}
```

```{r}
ggsave("~/Desktop/female_weights_gobp_full_zscore_heatmap.pdf", width = 12, height = 8, 
       plot = make_heatmap(mwgobp, 'female'))
```

```{r}
ggsave("~/Desktop/male_weights_gobp_full_zscore_heatmap.pdf", width = 12, height = 8, 
       plot = make_heatmap(mwgobp, 'male'))
```

```{r}
ggsave("~/Desktop/female_weights_mwdisc_full_zscore_heatmap.pdf", width = 12, height = 8, 
       plot = make_heatmap(mwdisc, 'female'))
```

```{r}
ggsave("~/Desktop/male_weights_mwdisc_full_zscore_heatmap.pdf", width = 12, height = 8, 
       plot = make_heatmap(mwdisc, 'male'))
```

```{r}
ggsave("~/Desktop/female_weights_mwmp_full_zscore_heatmap.pdf", width = 12, height = 8, 
       plot = make_heatmap(mwmp, 'female'))
```

```{r}
ggsave("~/Desktop/male_weights_mwmp_full_zscore_heatmap.pdf", width = 12, height = 8, 
       plot = make_heatmap(mwmp, 'male'))
```

```{r}
ggsave("~/Desktop/female_weights_mwgwas_full_zscore_heatmap.pdf", width = 12, height = 8, 
       plot = make_heatmap(mwgwas, 'female'))
```

```{r}
ggsave("~/Desktop/male_weights_mwgwas_full_zscore_heatmap.pdf", width = 12, height = 8, 
       plot = make_heatmap(mwgwas, 'male'))
```


```{r}
mono_term_heatmap <- function(df, s){
  df <- df %>% filter(sex == s)
  
  out <- tibble(term_id = "t", ag_cor = 0.8)
  for (t in unique(df$term_id)){
    tdf <- df %>% filter(term_id == t)
    c <- cor(tdf$zscore, tdf$ag_number, method = "spearman")
    tout <- tibble(term_id = t, ag_cor = c)
    out <- bind_rows(out, tout)
  }
  out <- out[-1,]
  keep_terms <- out %>% filter(abs(ag_cor) > 0.8) %>% pull(term_id)
    
  cut_df <- df %>% 
    filter(sex == s) %>% 
    mutate(zscore = ifelse(zscore > 5, 5, zscore)) %>% 
    mutate(zscore = ifelse(zscore < -5, -5, zscore)) %>% 
    filter(term_id %in% keep_terms)
  
  df_terms <- tibble(term_id = unique(cut_df$term_id), term_num = c(1:length(unique(cut_df$term_id))))
  cut_df <- left_join(cut_df, df_terms, by = "term_id")
  
  cut_mat <- as.matrix(with(cut_df, sparseMatrix(ag_number, term_num, x=zscore)))

  plot <- pheatmap(cut_mat, display_numbers = F, color = brbg_palette)
  
  return(plot)
}
```

```{r}
mono_term_heatmap(mwgobp, 'female')
```

```{r}
make_bar_plot <- function(df){
  fdf <- df %>% 
    filter(sex == 'female') %>% 
    filter(abs(zscore) > 3) %>% 
    group_by(age_range) %>% 
    tally()
  fdf$bias <- 'female'
  
  mdf <- df %>% 
    filter(sex == 'male') %>% 
    filter(abs(zscore) > 3) %>% 
    group_by(age_range) %>% 
    tally()
  mdf$bias <- 'male'
  
  df <- bind_rows(fdf, mdf)
  
  plot <- df %>% 
    ggplot(aes(x = factor(age_range, levels = age_ranges), y = n, fill = bias)) +
    geom_col(position = position_dodge(width = 1)) +
    scale_fill_manual(values = fm_palette) +
    geom_text(aes(label = n), position = position_dodge(width = 1), vjust = 0) + 
    theme(axis.title = element_blank(),
          panel.background = element_rect(fill = "white"),
          panel.grid = element_line(size = 0.2, colour = "lightgray"),
          text = element_text(size = 20))
}
```

```{r}
ggsave("~/Desktop/mwgobp_bar_plot.pdf", width = 12, height = 8,
       plot = make_bar_plot(mwgobp))
```

```{r}
ggsave("~/Desktop/mwdisc_bar_plot.pdf", width = 12, height = 8,
       plot = make_bar_plot(mwdisc))
```

```{r}
ggsave("~/Desktop/mwmp_bar_plot.pdf", width = 12, height = 8,
       plot = make_bar_plot(mwmp))
```

```{r}
ggsave("~/Desktop/mwgwas_bar_plot.pdf", width = 12, height = 8,
       plot = make_bar_plot(mwgwas))
```
