---
title: "gobp enrichment"
author: "Kayla Johnson"
date: '2022-06-14'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(knitr)
library(kableExtra)
library(UpSetR)
library(tidyverse)
library(RColorBrewer)
library(pheatmap)
library(colorspace)
```

```{r data_read, include=FALSE}
# read enrichment results
mwgobp <- read_tsv("../../results/elasticnet_LR_model_weights/gobp_enrichment.tsv") %>% 
  rename(zscore = combined_zscore) %>% 
  rename(term_id = term)

# line to make palette with colorspace gui
# choose_palette(pal = diverging_hcl, n = 7L, parent = NULL, gui = "tcltk")

# blue/orange palette
light_bo_div <- diverge_hcl(11, c = 100, h = c(260, 35), l = c(50, 90), rev = T)
# dark colors hex codes blue "#1c4587ff"/ orange "#783f04ff"
#blue/orange using on slides for M/F
fm_palette <- c("#6fa8dcff", "#e69138ff")

# order of age groups
fine_ag_order <- c("fetus", "infant", "young_child", "child", 
                                   "adolescent", "young_adult", "adult", 
                                   "middle_adult", "older_adult", "old_adult", "elderly")

age_ranges <- c("< 0", "[0-2]", "(2-8]", "(8-12]", "(12-20]", 
                "(20-35]", "(35-45]", "(45-60]", "(60-70]", "(70-80]", "> 80")

ar_tibble <- tibble(age_group = fine_ag_order, age_range = age_ranges, ag_number = c(1:11))

# add age range col to mwgobp
mwgobp <- left_join(mwgobp, ar_tibble, by = "age_group")

# read go term names in
go_terms <- read_tsv("../../data/gene_sets/GOBPs/GO__propagated-annotations__term-size10-200__Homo_sapiens__Entrez__BP__EXP_IDA_IPI_IMP_IGI_TAS_IC.tsv") %>% 
  select(go_id, go_name)
colnames(go_terms) <- c("term_id", "term_name")

# add term names to mwgobp
mwgobp <- left_join(mwgobp, go_terms, by = "term_id")
# two GO IDs do not have term names, because they were replaced 
# this gets rid of them (replacements exist in data)
mwgobp <- mwgobp %>% 
  filter(!is.na(term_name))
```
