---
title: "mwgwas enrichment"
author: "Kayla Johnson"
date: '2022-06-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(knitr)
library(tidyverse)
library(RColorBrewer)
library(pheatmap)
library(colorspace)
```

```{r data_read, include=FALSE}
# read enrichment results
mwgwas <- read_tsv("../../results/elasticnet_LR_model_weights/gwas_enrichment.tsv") %>% 
  rename(zscore = combined_zscore) %>% 
  rename(term_id = term)

# line to make palette with colorspace gui
# choose_palette(pal = diverging_hcl, n = 7L, parent = NULL, gui = "tcltk")

brbg <- brewer.pal(11, "BrBG")
brbg_palette <- c(colorRampPalette(c(brbg[1], brbg[6]))(21),
    colorRampPalette(c(brbg[6], brbg[11]))(21)[-1])

# dark colors hex codes blue "#1c4587ff"/ orange "#783f04ff"
#blue/orange using on slides for M/F
fm_palette <- c("#6fa8dcff", "#e69138ff")

# order of age groups
fine_ag_order <- c("fetus", "infant", "young_child", "child", 
                                   "adolescent", "young_adult", "adult", 
                                   "middle_adult", "older_adult", "old_adult", "elderly")

age_ranges <- c("< 0", "[0-2]", "(2-8]", "(8-12]", "(12-20]", 
                "(20-35]", "(35-45]", "(45-60]", "(60-70]", "(70-80]", "> 80")

ar_tibble <- tibble(age_group = fine_ag_order, age_range = age_ranges, ag_number = c(1:11))

# add age range col to mwgwas
mwgwas <- left_join(mwgwas, ar_tibble, by = "age_group")

# cut extreme zscore values to reasonable range
# filter to zscores of at least 2
mwgwas <- mwgwas %>% 
  #mutate(zscore = ifelse(zscore > 5, 5, zscore)) %>% 
  #mutate(zscore = ifelse(zscore < -5, -5, zscore)) %>% 
  filter(abs(zscore) > 3)
```

```{r}
mwgwas %>% filter(age_group %in% c('adult', 'young_adult')) %>% 
  arrange(sex, ag_number, desc(zscore)) %>% 
  View()
```



